Das U-Boot: Fork U-Boot v2024.10 to support OreSat am335x custom boards.
oresat/u-boot pull request #1
Opened 2024-11-11 23:20 UTC by chroco

Edit arch/arm/mach-omap2/Kconfig to include board/psas/oresat board files. Based on the am335x_evm section of this file.

Copy board/ti/ to board/psas/. This includes the common directory and is the template for the oresat family of boards.

Edit board/psas/oresat/Kconfig to use the correct files and to source board/psas/common/Kconfig during build.

Modify board.c board.h and mux.c in board/psas/oresat to boot oresat specific boards from the board and version strings found in the EEPROM. This commit also comments out the replaced code and preserves it for future reference.

Add configs/am335x_oresat_defconfig. This is the base configuraton file u-boot uses to build images. CONFIG_OF_LIST is commented out since it is not used in the current configuration but might be used in the future.

Copy arch/arm/dts/am335x-evm.dts to arch/arm/dts/am335x-oresat.dts and custommize the file. This is the default .dts u-boot uses on startup. Set CONFIG_DEFAULT_DEVICE_TREE="am335x-oresat" inam335x_oresat_defconfig. This .dtb is later replaced from the linux file system in /boot/dtbs/.

Copy include/configs/am335x_evm.h to include/configs/am335x_oresat.h and edit the script to determine which .dtb to load. This script is embedded in a macro as a string and passed the to the u-boot environment.

Add support for oresat-bbb-dev.dtb on the beaglebone black. The .dtb is included in /boot/dtbs during the image builder process. Selection takes place in include/configs/am335x_oresat.h. This .dtb was added for testing purposes and can be used instead of am335x_boneblack.dtb on the beaglebone black by modifying the board and version in the EEPROM.

2024-11-17 01:07 UTC, ThirteenFish requested changes
I'm still working through the technical parts, but in the meantime I have some requests on style:
 - Prefer deleting code instead of commenting it out. This shows up in diffs and there's no need to keep around dead code. It will always be preserved in git history.
 - Try to mimic the existing code style.
   - It uses a single tab instead of two spaces for indent
   - `if` statements have the braces at the end of the line instead of the following line: `if (foo) {`
   - Single line `if`s omit braces
   - Trim whitespace at the trailing ends of lines, either spaces after the end of text or blank lines with only spaces/tabs on them
   - Leave comment style as is, they typically use block `/**/` over line `//`
 - `CONFIG_XPL_BUILD` is undefined. This symbol appears to have been introduced in a patch on October 11th but this repo is forked off of the release on October 7. I think it's good to base off of a stable release so we'll probably want to update this patch. When v2025.01 comes out we'll have to remember to convert back from `SPL` to `XPL`.

2024-11-17 02:20 UTC, ThirteenFish commented
On a more technical level it looks like almost all the custom board changes are deleting configs for unused boards and extending all the places that look for `board_is_bone_lt()` to also `board_is_oresat()`? What advantage does creating a whole new set of boards offer over extending `board_is_bone_lt()` (and `board_late_init()`) to look for Oresat boards?

2024-11-17 13:45 UTC, chroco commented
> * Prefer deleting code instead of commenting it out. This shows up in diffs and there's no need to keep around dead code. It will always be preserved in git history.

I only left the comments in for the review. I thought it would make it easier to see the changes since there was a lot.

>   * Leave comment style as is, they typically use block `/**/` over line `//`

I'll put them back but it looks like I have to rework this whole PR again. Single line block comments are the worst (ever) when you're experimenting with code because you have to remove them to comment out blocks.

> * `CONFIG_XPL_BUILD` is undefined. This symbol appears to have been introduced in a patch on October 11th but this repo is forked off of the release on October 7. I think it's good to base off of a stable release so we'll probably want to update this patch. When v2025.01 comes out we'll have to remember to convert back from `SPL` to `XPL`.

I'll have to take a look at this. I'm not sure how the date got goofed up since I cloned v2024.10 and redid the entire pull from scratch because I changed to u-boot instead of the beaglebone u-boot. Is v2024.10 not a stable release? I picked this because I thought it was the last stable release before v2025.xx

2024-11-17 15:12 UTC, chroco commented
> On a more technical level it looks like almost all the custom board changes are deleting configs for unused boards and extending all the places that look for `board_is_bone_lt()` to also `board_is_oresat()`? What advantage does creating a whole new set of boards offer over extending `board_is_bone_lt()` (and `board_late_init()`) to look for Oresat boards?

I'm not sure if there is an advantage to it or not. I may have more insight on this when I get deeper into A/B boot. I can easily extend the functionality in the existing boards/ti/am335x directory and scrap adding new board files altogether. It could be done with a patch file like it is in the current oresat-linux. However, I would still like to see the u-boot repo added as a submodule for development purposes. If we decide keep the boards/psas/oresat I can probably get rid of boards/psas/common and just fix the Makefiles. I originally did this due to sloth, because copying the directory was easier than fixing the Makefiles:/

I'm not attached to either design choice, I want it to do it the right way. What are your thoughts now that you've had a chance to look through the code?

2024-11-17 19:44 UTC, ThirteenFish commented
> I only left the comments in for the review. I thought it would make it easier to see the changes since there was a lot.

For reference my review process here is copying `boards/psas/*` back into `boards/ti/am335/*` and looting at the output of `git diff`. Block commented code shows up as two green `/*` lines split across hunks whereas the deleted code shows up as a large bright red removed hunk. When needed I need additional context I swap back to the actual code instead of diffs, in this case deleting doesn't, it shows up clearly in the diffs, but block comments need the full context.
 
> I'll put them back but it looks like I have to rework this whole PR again. Single line block comments are the worst (ever) when you're experimenting with code because you have to remove them to comment out blocks.

I do agree, I prefer using either where they're easier too. It's fine to use line comments while experimenting as long as you remember to fix them up before pushing the PR.
 
> I'll have to take a look at this. I'm not sure how the date got goofed up since I cloned v2024.10 and redid the entire pull from scratch because I changed to u-boot instead of the beaglebone u-boot. Is v2024.10 not a stable release? I picked this because I thought it was the last stable release before v2025.xx

As far as I can tell v2024.10 is stable, but then they're going to make some changes before v2025.01. It looks like maybe you started working from the head of master and then went back to v2024.10 or possibly master in the beaglebone u-boot repo?
 
> I'm not sure if there is an advantage to it or not. I may have more insight on this when I get deeper into A/B boot. I can easily extend the functionality in the existing boards/ti/am335x directory and scrap adding new board files altogether. It could be done with a patch file like it is in the current oresat-linux. However, I would still like to see the u-boot repo added as a submodule for development purposes. If we decide keep the boards/psas/oresat I can probably get rid of boards/psas/common and just fix the Makefiles. I originally did this due to sloth, because copying the directory was easier than fixing the Makefiles:/
> 
> I'm not attached to either design choice, I want it to do it the right way. What are your thoughts now that you've had a chance to look through the code?

I think keeping u-boot as a submodule is fine. I'm also very curious about A/B boot and if that requires a new board then we must create a new board. I've not evaluated that yet.

If we don't need a new board then I'd much rather maintain a 40 line patch to an existing one instead of a 4,000 line patch that adds a new board.

2024-11-17 23:37 UTC, ThirteenFish commented
Additionally it appears that `am335x-oresat.dts` is based on `am335x-boneblack.dts` and not `am335x-evm.dts` as mentioned in the commit message.

2024-11-19 01:16 UTC, ThirteenFish commented on board/psas/oresat/board.c
> +  }
This change doesn't reflect the intended behavior of the function. If I understand correctly this function answers the question "Does the current board I'm running on require the device tree named in `name`". That's why all the `strcmp()` are there. This picks the first device tree and says yes, this one is mine.

2024-11-19 01:42 UTC, ThirteenFish commented on configs/am335x_oresat_defconfig
`defconfigs` are like the default starting point configs for individual projects to modify. Since we'll probably want to do a bunch of modifications ourselves the config should probably live in `oresat-linux` (and not be named `_defconfig`). This will also help with change visibility, we'll want to separate out our specific config from u-boot patches. Also we'll not really want to update the submodule every time we make a config change. You can pass an arbitrary config to a Kbuild system through the environment variable `KCONFIG_CONFIG` so for example `KCONFIG_CONFIG=am335x_oresat_config make -C u-boot`.

2024-12-27 14:24 UTC, chroco commented
Closing this PR and starting a new branch (feature/boot_oresat_boards_revision) to make the requested changes.

2024-12-27 14:24 UTC, closed without merging